### PR TITLE
fix: createElementNS polyfill

### PR DESCRIPTION
**Pull request by adevnadia**

### CODE REVIEW

**Comment by joscha** [comment]
LGTM

**Comment by jpnelson** [comment]
LGTM

**Comment by jpnelson** [comment]
I'd be interested to find out how this caused problems, though. Was something using createElementNS?

**Comment by adevnadia** [comment]
Yep, incrementalDOM uses it to create elements

**Comment by joscha** [comment]
Browserstack seems to have some hiccups, I don't have the credentials to look at what actually is the problem - @treshugart can you have a look?

**Comment by treshugart** [comment]
@joscha looking now

UPDATE

Looks like it was a hung build. Restarted.

**Pull request merged**
