### PR TITLE
#8 - Implement slotchange event

### PR DESCRIPTION
**Pull request by treshugart**
### Overview

This is a somewhat naive implementation of #8 (discussion: https://github.com/w3c/webcomponents/issues/288) since this feature is still being discussed for the spec. This PR implements the `slotchange` event as per the open discussion:
- Async
- Event-based
- Fires once for all sync changes
### Implementation details

Both `addEventListener` and `removeEventListener` are patched to keep track of if there are any `slotchange` events being listened to so that we don't have to fire the event if there are no listeners which saves us a significant amount of overhead.

### CODE REVIEW

**Comment by jpnelson** [comment]
What will the `addedNodes` look like for nested slots? The spec mentions some flattening logic?

Otherwise, looks good to me.

**Comment by treshugart** [comment]
Slots have `getDistributedNodes()` and `getDistributedNodes({ flatten: true })` right? I'm not 100% clear, but from reading that thread it seems that you only get direct descendants that are slotted into the `<slot>` that you've bound the event to. If that's the case, then `addedNodes` and `removedNodes` would be nodes found in `getDistributedNodes()`. I'm not sure there is a use case for getting flattened nodes in those lists.

**Comment by treshugart** [comment]
I've updated so that it doesn't include information about changed nodes anymore because we can just `getAssignedNodes()` if we want to.

**Comment by jpnelson** [comment]
LGTM

**Pull request merged**
